# SPDX-FileCopyrightText: 2026 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

name: Todosaurus
description: Check the TODO comments in the repository according to the validation rules in the configuration file.
branding:
  icon: list
  color: yellow

inputs:
  config:
    description: Path to the configuration file.
    required: true
    default: ${{ github.workspace }}/todosaurus.toml

  strict:
    description: Enable strict mode for validation.
    required: false
    default: "false"

  github-token:
    description: Token to fetch the issues from the current repository. Helps to avoid rate-limiting by GitHub.
    required: false

runs:
  using: composite
  steps:
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ${{ github.action_path }}/../global.json

    - name: Run Todosaurus
      shell: pwsh
      working-directory: ${{ github.action_path }}
      run: dotnet run --project ../cli/Cli/Cli.fsproj -- scan --config $env:CONFIG_PATH ${{ inputs.strict == 'true' && '--strict' || '' }}
      env:
        CONFIG_PATH: ${{ inputs.config }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
