# SPDX-FileCopyrightText: 2000-2021 JetBrains s.r.o.
# SPDX-FileCopyrightText: 2024 Todosaurus contributors <https://github.com/ForNeVeR/Todosaurus>
#
# SPDX-License-Identifier: Apache-2.0

[versions]
ideaSdk = "2024.3"
ideaSdkPreview = "2024.3.2"
kotlin = "2.0.21"

[libraries]
junit = "junit:junit:4.13.2"
openTest4J = "org.opentest4j:opentest4j:1.3.0"

[plugins]
changelog = "org.jetbrains.changelog:2.2.1"
gradleIntelliJPlatformPlugin = "org.jetbrains.intellij.platform:2.2.1"
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.14.0"
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = "org.jetbrains.qodana:2024.3.4"
