[versions]
kotlin = "1.9.22"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.17.2"
qodana = "0.1.13"

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
gradleJvmWrapper = { id = "me.filippov.gradle.jvm.wrapper", version = "0.14.0" }
