# SPDX-FileCopyrightText: 2000-2021 JetBrains s.r.o.
# SPDX-FileCopyrightText: 2024 Todosaurus contributors <https://github.com/ForNeVeR/Todosaurus>
#
# SPDX-License-Identifier: Apache-2.0

name: Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  # Prepare and publish the plugin to JetBrains Marketplace repository
  release:
    name: Publish Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Read version from Git ref
        id: version
        shell: pwsh
        run: echo "version=$(if ($env:GITHUB_REF.StartsWith('refs/tags/v')) { $env:GITHUB_REF -replace '^refs/tags/v', '' } else { 'next' })" >> $env:GITHUB_OUTPUT

      # Check out the current repository
      - name: Fetch Sources
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Read the changelog
        uses: ForNeVeR/ChangelogAutomation.action@v2
        with:
          input: ./CHANGELOG.md
          output: ./changelog-section.md

      - name: 'Cache downloaded JDK'
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/gradle-jvm
            ~/AppData/Local/gradle-jvm
          key: ${{ runner.os }}-${{ hashFiles('gradlew*') }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-home-cache-cleanup: true

      - name: 'Build the plugin'
        shell: pwsh
        run: ./gradlew buildPlugin

      - name: Upload the artifact
        uses: actions/upload-artifact@v5
        with:
          name: Todosaurus-${{ steps.version.outputs.version }}.zip
          path: build/distributions/Todosaurus-${{ steps.version.outputs.version }}.zip

      - name: Upload the changelog
        uses: actions/upload-artifact@v5
        with:
          name: changelog-section.md
          path: ./changelog-section.md

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Create the release
        shell: pwsh
        run: scripts/New-Release.ps1 -Version $env:VERSION -ReleaseNotesFilePath ./changelog-section.md -FileToUpload $env:FILE_TO_UPLOAD
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ steps.version.outputs.version }}
          FILE_TO_UPLOAD: build/distributions/Todosaurus-${{ steps.version.outputs.version }}.zip

      # Publish the plugin to JetBrains Marketplace
      - if: startsWith(github.ref, 'refs/tags/v')
        name: Publish the plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin
